name: Test Lab submissions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.9 
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test code 
        run: |
          python3 test_all.py
